services:
  warehouse:
    image: postgres:16
    container_name: soluna_warehouse
    environment:
      POSTGRES_USER: soluna
      POSTGRES_PASSWORD: soluna
      POSTGRES_DB: soluna
    ports:
      - "5432:5432"
    volumes:
      - warehouse_data:/var/lib/postgresql/data
      - ./data:/data:ro
      - ./sql:/sql:ro

  adminer:
    image: adminer:4
    container_name: soluna_adminer
    ports:
      - "8080:8080"
    depends_on:
      - warehouse

volumes:
  warehouse_data: